export const checklists = [
	{
		aircraft: 'F-45A',
		hidden: false,
		checklists: [
			{
				type: 'aircraft',
				name: 'Startup',
				file: 'f45-startup.md',
				related: [
					'f45-takeoff-runway.md',
					'f45-takeoff-CATOBAR.md',
					'f45-short-takeoff.md',
					'f45-vcap.md',
				],
				hidden: false,
				showGlobal: false,
				showEmergencies: false,
			},
			{
				type: 'aircraft',
				name: 'Takeoff (RWY)',
				file: 'f45-takeoff-runway.md',
				hidden: false,
				showGlobal: false,
				showEmergencies: true,
			},
			{
				type: 'aircraft',
				name: 'Landing (RWY)',
				file: 'f45-landing-runway.md',
				hidden: false,
				showGlobal: false,
				showEmergencies: true,
			},
			{
				type: 'aircraft',
				name: 'Takeoff (CARRIER)',
				file: 'f45-takeoff-CATOBAR.md',
				related: [
					'carrier-departure.md',
					'flightdeck-overview.md',
					'case-1.md',
				],
				hidden: false,
				showGlobal: false,
				showEmergencies: true,
			},
			{
				type: 'page',
				name: 'Landing (CARRIER)',
				file: 'f45-landing-CATOBAR-preface.md',
				related: [
					'marshal.md',
					'case-1-final.md',
					'f45-landing-CATOBAR.md',
					'case-1.md',
				],
				for: 'aircraft',
				hidden: false,
				showGlobal: true,
				showEmergencies: false,
			},
			{
				type: 'aircraft',
				name: 'Carrier Landing - CASE I',
				file: 'f45-landing-CATOBAR.md',
				hidden: true,
				showGlobal: true,
				showEmergencies: true,
			},
			{
				type: 'page',
				name: 'V/STOL',
				file: 'f45-svtol.md',
				related: ['f45-short-takeoff.md', 'f45-vtol-landing.md'],
				for: 'aircraft',
				hidden: false,
				showGlobal: true,
				showEmergencies: false,
			},
			{
				type: 'aircraft',
				name: 'Short Takeoff',
				file: 'f45-short-takeoff.md',
				related: ['f45-vtol-landing.md'],
				hidden: true,
				showGlobal: false,
				showEmergencies: true,
			},
			{
				type: 'aircraft',
				name: 'Vertical Landing',
				file: 'f45-vtol-landing.md',
				hidden: true,
				showGlobal: false,
				showEmergencies: true,
			},
			{
				type: 'aircraft',
				name: 'VCAP',
				file: 'f45-vcap.md',
				related: ['f45-vtol-landing.md'],
				hidden: false,
				showGlobal: false,
				showEmergencies: true,
			},
		],
	},
	{
		aircraft: 'carrier',
		hidden: true,
		checklists: [
			{
				type: 'global',
				name: 'Flight Deck Overview',
				file: 'flightdeck-overview.md',
				showGlobal: true,
				hidden: false,
			},
			{
				type: 'global',
				name: 'Departure',
				file: 'carrier-departure.md',
				showGlobal: false,
				hidden: true,
			},
			{
				type: 'page',
				for: 'carrier',
				name: 'Carrier Operations',
				file: 'carrier-ops.md',
				showGlobal: true,
				hidden: false,
			},
			{
				type: 'global',
				name: 'Wave Off',
				file: 'wave-off.md',
				showGlobal: true,
				showEmergencies: true,
				hidden: false,
			},
			{
				type: 'global',
				name: 'LSO Guidance',
				file: 'lso-guidance.md',
				related: ['wave-off.md'],
				showGlobal: true,
				hidden: false,
			},
			{
				type: 'global',
				name: 'Carrier Lights (Meatball) Img',
				file: 'meatball.md',
				showGlobal: true,
				hidden: false,
			},
			{
				type: 'page',
				name: 'Case 1 Ops',
				file: 'case-1.md',
				related: [
					'carrier-departure.md',
					'marshal.md',
					'case-1-final.md',
				],
				for: 'carrier-ops.md',
				showGlobal: true,
				hidden: true,
			},
			{
				type: 'global',
				name: 'Marshal Stack Pattern',
				file: 'marshal.md',
				related: ['case-1-final.md', 'meatball.md'],
				showGlobal: false,
				hidden: true,
			},
			{
				type: 'global',
				name: 'Final Approach',
				file: 'case-1-final.md',
				showGlobal: false,
				hidden: true,
			},
		],
	},
]

export const emergencyChecklists = [
	{
		aircraft: 'F-45A',
		checklists: [
			{
				type: 'emergency',
				name: 'Engine Failure',
				file: 'f45-emerg-enginefailure.md',
			},
			{
				type: 'emergency',
				name: 'Missile Impact',
				file: 'f45-emerg-missileimpact.md',
			},
			{
				type: 'emergency',
				name: 'Flight Control Failure',
				file: 'f45-emerg-flightcontrol.md',
			},
		],
	},
]
